version: '3.7'
services:
  booksonic-air:
    image: linuxserver/booksonic-air:latest
    container_name: booksonic-air
    hostname: booksonic-air
    restart: unless-stopped
    volumes:
      - ../Data/config:/config
      - ../Data/audiobooks:/audiobooks
      - ../Data/podcasts:/podcasts
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - JAVA_OPTS=-Dserver.use-forward-headers=true
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.booksonic-air.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.booksonic-air.entrypoints=web-secure"
      - "traefik.http.routers.booksonic-air.service=booksonic-air"
      - "traefik.http.routers.booksonic-air.tls=true"
      - "traefik.http.services.booksonic-air.loadbalancer.server.port=4040" # Proxied Port
